<a href="https://colab.research.google.com/github/Aman2125/Numpy_CampusX_Practice/blob/main/1)aman_numpybasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([1,2,3])
print(a) #1D array

[1 2 3]


In [ ]:
#2D and 3D array
b = np.array([[1,2,3] , [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D also called tenser
c = np.array([[1,2] , [3,4] , [5,6]])
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#dtype that changine int to other variables
a=np.array([1,2,3] , dtype=bool)
b=np.array([1,2,3] , dtype=float)
c=np.array([1,2,3] , dtype=complex)

print(a)
print(b)
print(c)

[ True  True  True]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
#np.arange , also method for creating array , like range in python
a = np.arange(1 ,11)
b = np.arange(1,11,2) #stride = 2

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
# with reshape , converts 1D to 2D
a = np.arange(1 ,11).reshape(5,2)
b = np.arange(1 ,11).reshape(2,5);

print(a)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# np.ones and np.zeros , all items 1 or 0 , used for initialization
a = np.ones((3,4)) #3rows and 4 col with 1,to initialize weights in NN
b = np.zeros((3,4))

print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# np.random , initialise numbers between 0 and 1 randomly
np.random.random((3,4))

array([[0.96416661, 0.89161061, 0.22157143, 0.0866453 ],
       [0.21177548, 0.14071592, 0.61472068, 0.21146096],
       [0.90173696, 0.18082857, 0.36633306, 0.13234287]])

In [ ]:
# np.linspace , 3 parameters peovided lower , upper range and number of items
np.linspace(-10,10,10) #eqidistance point generation

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity , used for creation of identity matrix
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Numpy or Array attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12 , dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)


[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#ndim for finding the dimension of array
a1.ndim
a2.ndim
a3.ndim

3

In [ ]:
#shape tells no of dimension exist in array
a1.shape
a2.shape


(3, 4)

In [ ]:
#size to find no of items in array
a3.size

8

In [ ]:
#itemsize
a1.itemsize


8

In [ ]:
#dtype tells about dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


#changing datatypes


In [ ]:
#astype
a3.astype(np.int32) #say age given so needed less space hence set to 32bit

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#scalar operation

#arithmetic
a1*2
a2+2

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [ ]:
#relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#vector operation

#arithmetic
a1+a2
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#Array Function

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[67., 39., 98.],
       [66., 78., 62.],
       [53., 18., 34.]])

In [ ]:
#max/min/sum/prod
np.sum(a1)
np.max(a1)
np.min(a1)
np.prod(a1)
np.max(a1 , axis=1) #for finding each row maxi
np.max(a1 , axis=0) #for finding each col maxi


array([67., 78., 98.])

In [ ]:
#mean/median/std/var

np.mean(a1 , axis=1) #for each row mean
np.var(a1)


np.float64(524.1728395061729)

In [ ]:
#trignometric functions
np.sin(a1)

array([[-0.85551998,  0.96379539, -0.57338187],
       [-0.02655115,  0.51397846, -0.7391807 ],
       [ 0.39592515, -0.75098725,  0.52908269]])

In [ ]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2 , a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponents
np.exp(a1)
np.log(a1)

array([[4.20469262, 3.66356165, 4.58496748],
       [4.18965474, 4.35670883, 4.12713439],
       [3.97029191, 2.89037176, 3.52636052]])

In [ ]:
#round/ceil/floor

a = np.random.random((2,3))*100
np.round(a)
np.floor(a)
np.ceil(a)

array([[39., 34.,  3.],
       [62., 72., 67.]])

#Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#last item , first item
a1[-1]
a1[1]

np.int64(1)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#finding some ele in 2d array
a2[1,2] #by defining row and col

np.int64(6)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#finding el in 3d

a3[1,0,1] #define first which 2d box then same as 2d one that is row and col

np.int64(5)

#Slicing

In [ ]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#finding range of el same as python
a1[2:5]
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#finding complete row in 2d
a2[0,:] #1st row

array([0, 1, 2, 3])

In [ ]:
#find 5,6 and 9,10 in a2
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#find middle 2d array
a3[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
#find 1st and last
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#find 2nd row of 1st 2d array in a3
a3[0 , 1]

array([3, 4, 5])

#Interating

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3
for i in a3 :
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
#nditer for printing all el in 2d and 3d arr
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [ ]:
#reshape


In [ ]:
#transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#ravel , coverts all dimension array into 1d array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#Stacking

In [ ]:
#horizontal stacking means just piling up , shape must be same
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Splitting

In [ ]:
#horizontal splitting , spilitting up of stacked array
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4 , 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
#vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5 , 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]